#!/bin/bash

# Name: auto-knight
# Description: This script automatically changes the global theme and wallpaper of
# KDE Plasma based on the time of day. It utilizes KDE's built-in
# Night Light feature to determine whether it is day or night.
# The script is intended to be autostarted.
# Author: Dmitriy Safiullin

# plasma-apply-lookandfeel --list # to list available themes
# theme and command settings
LIGHT_THEME="com.github.vinceliuice.Layan-light"
DARK_THEME="com.github.vinceliuice.Layan"
CHANGE_THEME_COMMAND="plasma-apply-lookandfeel -a"

# cursor theme settings
LIGHT_CURSOR="Breeze_Light"
DARK_CURSOR="breeze_cursors"
CHANGE_CURSOR_COMMAND="plasma-apply-cursortheme"

# wallpaper settings
LIGHT_WALLPAPER="/home/wcs/.local/share/wallpapers/Windots/walls/beach-path.jpg"  # Replace with your light wallpaper path
DARK_WALLPAPER="/home/wcs/.local/share/wallpapers/Windots/walls/stall.jpg"    # Replace with your dark wallpaper path
CHANGE_WALLPAPER_COMMAND="plasma-apply-wallpaperimage"

# sets theme, cursor and wallpaper and updates state
set_theme_and_wallpaper() {
    $CHANGE_THEME_COMMAND "$1"
    $CHANGE_CURSOR_COMMAND "$2"
    $CHANGE_WALLPAPER_COMMAND "$3"
    LAST_THEME="$1"
}

# retrieves current daylight status
is_daylight() {
    local daylight_status
    daylight_status=$(qdbus org.kde.KWin /org/kde/KWin/NightLight \
        org.kde.KWin.NightLight.daylight)
    [[ "$daylight_status" == "true" ]]
}

# initializes the theme, cursor and wallpaper based on the current daylight status
initialize_theme_and_wallpaper() {
    if is_daylight; then
        set_theme_and_wallpaper "$LIGHT_THEME" "$LIGHT_CURSOR" "$LIGHT_WALLPAPER"
    else
        set_theme_and_wallpaper "$DARK_THEME" "$DARK_CURSOR" "$DARK_WALLPAPER"
    fi
}

# monitors changes in daylight status and updates the theme, cursor and wallpaper accordingly
monitor_daylight_changes() {
    dbus-monitor --session \
        "type='signal',interface='org.freedesktop.DBus.Properties', \
        member='PropertiesChanged', path='/org/kde/KWin/NightLight'" |
        grep --line-buffered "daylight" |
        while read -r line; do
            if is_daylight; then
                [[ "$LAST_THEME" != "$LIGHT_THEME" ]] && set_theme_and_wallpaper "$LIGHT_THEME" "$LIGHT_CURSOR" "$LIGHT_WALLPAPER"
            else
                [[ "$LAST_THEME" != "$DARK_THEME" ]] && set_theme_and_wallpaper "$DARK_THEME" "$DARK_CURSOR" "$DARK_WALLPAPER"
            fi
        done
}

initialize_theme_and_wallpaper
monitor_daylight_changes
