#!/bin/bash

# Name: auto-knight
# Description: This script automatically changes the global theme and wallpaper of
# KDE Plasma based on the time of day. It utilizes KDE's built-in
# Night Light feature to determine whether it is day or night.
# The script is intended to be autostarted.
# Author: Dmitriy Safiullin

# plasma-apply-lookandfeel --list # to list available themes
# theme and command settings
LIGHT_THEME="com.github.vinceliuice.Layan-light"
DARK_THEME="com.github.vinceliuice.Layan"
CHANGE_THEME_COMMAND="plasma-apply-lookandfeel -a"

# Kvantum theme settings
LIGHT_KVANTUM="Layan"
DARK_KVANTUM="LayanDark"
CHANGE_KVANTUM_COMMAND="kvantummanager --set"

# GTK theme settings
LIGHT_GTK="Breeze"
DARK_GTK="Breeze-Dark"
CHANGE_GTK3_COMMAND="dbus-send --session --dest=org.kde.GtkConfig --type=method_call /GtkConfig org.kde.GtkConfig.setGtk3Theme"
CHANGE_GTK2_COMMAND="dbus-send --session --dest=org.kde.GtkConfig --type=method_call /GtkConfig org.kde.GtkConfig.setGtk2Theme"

# cursor theme settings
LIGHT_CURSOR="Breeze_Light"
DARK_CURSOR="breeze_cursors"
CHANGE_CURSOR_COMMAND="plasma-apply-cursortheme"

# wallpaper settings
LIGHT_WALLPAPER="/home/$USER/.local/share/wallpapers/Windots/walls/beach-path.jpg"  # Replace with your light wallpaper path
DARK_WALLPAPER="/home/$USER/.local/share/wallpapers/Windots/walls/stall.jpg"    # Replace with your dark wallpaper path
CHANGE_WALLPAPER_COMMAND="plasma-apply-wallpaperimage"

# sets theme, cursor and wallpaper and updates state
set_theme() {
    $CHANGE_THEME_COMMAND "$1"
    $CHANGE_KVANTUM_COMMAND "$2"
    $CHANGE_GTK3_COMMAND "'string:$3'"
    $CHANGE_GTK2_COMMAND "'string:$3'"
    $CHANGE_CURSOR_COMMAND "$4"
    $CHANGE_WALLPAPER_COMMAND "$5"
    # restart_kde
}

# restarts KDE
# restart_kde() {
#     # kquitapp5 plasmashell || killall plasmashell && kstart5 plasmashell
#     kquitapp6 plasmashell && kstart plasmashell
# }

# retrieves current daylight status if it is true then it is day, otherwise it is night
is_daylight() {
    local daylight_status
    daylight_status=$(qdbus org.kde.KWin /org/kde/KWin/NightLight \
        org.kde.KWin.NightLight.daylight)
    [[ "$daylight_status" == "true" ]]
}

# checks if theme needs to be updated based on daylight status
should_update_theme() {
    current_theme=$(kreadconfig5 --key LookAndFeelPackage)
    if is_daylight; then
        [[ "$current_theme" != "$LIGHT_THEME" ]]
    else
        [[ "$current_theme" != "$DARK_THEME" ]]
    fi
}

# updates theme and wallpaper based on daylight status
update_theme() {
    if is_daylight; then
        set_theme "$LIGHT_THEME" "$LIGHT_KVANTUM" "$LIGHT_GTK" "$LIGHT_CURSOR" "$LIGHT_WALLPAPER"
    else
        set_theme "$DARK_THEME" "$DARK_KVANTUM" "$DARK_GTK" "$DARK_CURSOR" "$DARK_WALLPAPER"
    fi
}

# initializes the theme, cursor and wallpaper based on the current daylight status
initialize_theme() {
    should_update_theme && update_theme
}

# monitors changes in daylight status and updates the theme, cursor and wallpaper accordingly
monitor_daylight_changes() {
    dbus-monitor --session \
        "type='signal',interface='org.freedesktop.DBus.Properties', \
        member='PropertiesChanged', path='/org/kde/KWin/NightLight'" |
        grep --line-buffered "daylight" |
        while read -r line; do
            should_update_theme && update_theme
        done
}

initialize_theme
monitor_daylight_changes
