#!/bin/bash

# plasma-apply-lookandfeel --list # to list available themes
# theme and command settings
LIGHT_THEME="com.github.vinceliuice.Layan-light"
DARK_THEME="com.github.vinceliuice.Layan"
CHANGE_THEME_COMMAND="plasma-apply-lookandfeel -a"

# Konsole profile settings
LIGHT_KONSOLE="light.profile"
DARK_KONSOLE="dark.profile"
CHANGE_KONSOLE_COMMAND=("kwriteconfig6" "--file" "$HOME/.config/konsolerc" "--group" "Desktop Entry" "--key" "DefaultProfile") # Quotes/backslashes will be treated literally. use array to pass multiple arguments

# Kvantum theme settings
LIGHT_KVANTUM="Layan"
DARK_KVANTUM="LayanDark"
# CHANGE_KVANTUM_COMMAND="kvantummanager --set"

# GTK theme settings
LIGHT_GTK="Breeze"
DARK_GTK="Breeze"
CHANGE_GTK3_COMMAND="dbus-send --session --dest=org.kde.GtkConfig --type=method_call /GtkConfig org.kde.GtkConfig.setGtk3Theme"
CHANGE_GTK2_COMMAND="dbus-send --session --dest=org.kde.GtkConfig --type=method_call /GtkConfig org.kde.GtkConfig.setGtk2Theme"

# list available cursor themes # find /usr/share/icons ~/.local/share/icons ~/.icons -maxdepth 2 -type f -name "index.theme" | while read theme_file; do dirname "$theme_file" | xargs basename; done | sort -u
LIGHT_CURSOR="BreezeX-Light"
DARK_CURSOR="BreezeX-Dark"
CHANGE_CURSOR_COMMAND="plasma-apply-cursortheme"

# wallpaper settings
LIGHT_WALLPAPER="$HOME/.local/share/wallpapers/Windots/walls/beach-path.jpg"  # Replace with your light wallpaper path
DARK_WALLPAPER="$HOME/.local/share/wallpapers/Windots/walls/stall.jpg"    # Replace with your dark wallpaper path
# use kde Dynamic Wallpapers
# CHANGE_WALLPAPER_COMMAND="plasma-apply-wallpaperimage" 

# lockscreen wallpaper settings
LIGHT_LOCKSCREEN_WALLPAPER="$HOME/.local/share/wallpapers/Windots/walls/beach-path.jpg"  # Replace with your light lockscreen wallpaper path
DARK_LOCKSCREEN_WALLPAPER="$HOME/.local/share/wallpapers/Windots/walls/stall.jpg"    # Replace with your dark lockscreen wallpaper path
# use kde Dynamic Wallpapers
# CHANGE_LOCKSCREEN_WALLPAPER_COMMAND="kwriteconfig6 --file ~/.config/kscreenlockerrc --group General --key Wallpaper"

# brightness settings (values are integers passed to setBrightness)
LIGHT_BRIGHTNESS=4000
DARK_BRIGHTNESS=2000
CHANGE_BRIGHTNESS_COMMAND=("qdbus" "org.kde.Solid.PowerManagement" "/org/kde/Solid/PowerManagement/Actions/BrightnessControl" "setBrightness")

# sets theme, cursor and wallpaper and updates state
set_theme() {
    $CHANGE_THEME_COMMAND "$1"
    # $CHANGE_KVANTUM_COMMAND "$2"
    $CHANGE_GTK3_COMMAND "string:$3"
    $CHANGE_GTK2_COMMAND "string:$3"
    $CHANGE_CURSOR_COMMAND "$4"
    # $CHANGE_WALLPAPER_COMMAND "$5"
    # $CHANGE_LOCKSCREEN_WALLPAPER_COMMAND "file://$8"  # 8th parameter: lockscreen wallpaper
    "${CHANGE_KONSOLE_COMMAND[@]}" "$6" # @ is used to expand the array
    "${CHANGE_BRIGHTNESS_COMMAND[@]}" "$7"
    # restart_kde
}

# restarts KDE
restart_kde() {
    kquitapp6 plasmashell || killall plasmashell
    sleep 1
    kstart plasmashell
}

# check if it is dark theme
is_dark_theme() {
    current_theme=$(kreadconfig6 --key LookAndFeelPackage)
    if [[ "$current_theme" == "$DARK_THEME" ]]; then
        return 0 # true 命令成功执行时返回 0，返回其他值表示失败
    else
        return # false
    fi
}

# updates theme and wallpaper based on daylight status
update_theme() {
    if is_dark_theme; then
        set_theme "$LIGHT_THEME" "$LIGHT_KVANTUM" "$LIGHT_GTK" "$LIGHT_CURSOR" "$LIGHT_WALLPAPER" "$LIGHT_KONSOLE" "$LIGHT_BRIGHTNESS" "$LIGHT_LOCKSCREEN_WALLPAPER"
    else
        set_theme "$DARK_THEME" "$DARK_KVANTUM" "$DARK_GTK" "$DARK_CURSOR" "$DARK_WALLPAPER" "$DARK_KONSOLE" "$DARK_BRIGHTNESS" "$DARK_LOCKSCREEN_WALLPAPER"
    fi
}

update_theme
